import type { Metadata } from "next";
import { Montserrat, Geist_Mono } from "next/font/google";
import Navbar from "@/app/components/Navbar"; // Sesuaikan jalur foldernya jika berbeda
import WhatsAppFloat from "@/app/components/WhatsAppFloat";
import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sense Isle Studio - Interior & Architecture",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${montserrat.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-black text-white">
        {/* Navbar tampil di semua halaman */}
        <Navbar />

        {/* Konten halaman yang sedang dibuka (Home, Portfolio, dll) */}
        <main className="flex-grow">{children}</main>

        {/* Tombol WhatsApp mengapung di semua halaman */}
        <WhatsAppFloat />
      </body>
    </html>
  );
}
